// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDevice = "device"

// Device mapped from table <device>
type Device struct {
	ID           int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	MaintainerID int64     `gorm:"column:maintainer_id;type:int;not null" json:"maintainer_id"`
	HenhouseID   int64     `gorm:"column:henhouse_id;type:int;not null" json:"henhouse_id"`
	Status       int64     `gorm:"column:status;type:int;not null" json:"status"`
	Type         int64     `gorm:"column:type;type:int;not null" json:"type"`
	URL          string    `gorm:"column:url;type:varchar(500);not null" json:"url"`
	Mac          string    `gorm:"column:mac;type:varchar(20);not null" json:"mac"`
	Name         string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	CreateTime   time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
