// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "employee"

// Employee mapped from table <employee>
type Employee struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	Rank       int64     `gorm:"column:rank;type:int;not null" json:"rank"`
	Phone      string    `gorm:"column:phone;type:varchar(15);not null" json:"phone"`
	Openid     *string   `gorm:"column:openid;type:varchar(40)" json:"openid"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
