// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployeeAffiliation = "employee_affiliation"

// EmployeeAffiliation mapped from table <employee_affiliation>
type EmployeeAffiliation struct {
	ID           int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID   int64     `gorm:"column:employee_id;type:int;not null" json:"employee_id"`
	FarmID       int64     `gorm:"column:farm_id;type:int;not null" json:"farm_id"`
	EnterpriseID int64     `gorm:"column:enterprise_id;type:int;not null" json:"enterprise_id"`
	CreateTime   time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName EmployeeAffiliation's table name
func (*EmployeeAffiliation) TableName() string {
	return TableNameEmployeeAffiliation
}
