// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEnterprise = "enterprise"

// Enterprise mapped from table <enterprise>
type Enterprise struct {
	ID               int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	Address          string    `gorm:"column:address;type:varchar(500);not null" json:"address"`
	SuperintendentID int64     `gorm:"column:superintendent_id;type:int;not null" json:"superintendent_id"`
	CreateTime       time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName Enterprise's table name
func (*Enterprise) TableName() string {
	return TableNameEnterprise
}
