// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFarm = "farm"

// Farm mapped from table <farm>
type Farm struct {
	ID               int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	EnterpriseID     int64     `gorm:"column:enterprise_id;type:int;not null" json:"enterprise_id"`
	SuperintendentID int64     `gorm:"column:superintendent_id;type:int;not null" json:"superintendent_id"`
	Name             string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	Address          string    `gorm:"column:address;type:varchar(500);not null" json:"address"`
	CreateTime       time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName Farm's table name
func (*Farm) TableName() string {
	return TableNameFarm
}
