// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenStep = "hen_steps"

// HenStep mapped from table <hen_steps>
type HenStep struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UUID       string    `gorm:"column:uuid;type:varchar(40);not null" json:"uuid"`
	Mac        string    `gorm:"column:mac;type:varchar(20);not null" json:"mac"`
	Name       string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	HenhouseID int64     `gorm:"column:henhouse_id;type:int;not null" json:"henhouse_id"`
	DaySteps   int64     `gorm:"column:day_steps;type:int;not null" json:"day_steps"`
	TotalSteps int64     `gorm:"column:total_steps;type:int;not null" json:"total_steps"`
	Rssi       int64     `gorm:"column:rssi;type:int;not null" json:"rssi"`
	Battery    int64     `gorm:"column:battery;type:int;not null" json:"battery"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
}

// TableName HenStep's table name
func (*HenStep) TableName() string {
	return TableNameHenStep
}
