// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenhouseInOut = "henhouse_in_out"

// HenhouseInOut mapped from table <henhouse_in_out>
type HenhouseInOut struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	HenhouseID int64     `gorm:"column:henhouse_id;type:int;not null" json:"henhouse_id"`
	Amount     int64     `gorm:"column:amount;type:int;not null" json:"amount"`
	Days       int64     `gorm:"column:days;type:int;not null" json:"days"`
	Action     int64     `gorm:"column:action;type:tinyint(1);not null" json:"action"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	EmployeeID int64     `gorm:"column:employee_id;type:int;not null" json:"employee_id"`
	Sum        int64     `gorm:"column:sum;type:int;not null" json:"sum"`
}

// TableName HenhouseInOut's table name
func (*HenhouseInOut) TableName() string {
	return TableNameHenhouseInOut
}
