// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenhouse = "henhouse"

// Henhouse mapped from table <henhouse>
type Henhouse struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	FarmID     int64     `gorm:"column:farm_id;type:int;not null" json:"farm_id"`
	Longitude  float32   `gorm:"column:longitude;type:float;not null" json:"longitude"`
	Latitude   float32   `gorm:"column:latitude;type:float;not null" json:"latitude"`
	Name       string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	Sum        int64     `gorm:"column:sum;type:int;not null" json:"sum"`
}

// TableName Henhouse's table name
func (*Henhouse) TableName() string {
	return TableNameHenhouse
}
