// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryInOut = "inventory_in_out"

// InventoryInOut mapped from table <inventory_in_out>
type InventoryInOut struct {
	ID          int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	FarmID      int64      `gorm:"column:farm_id;type:int;not null" json:"farm_id"`
	Sum         int64      `gorm:"column:sum;type:int;not null" json:"sum"`
	InventoryID int64      `gorm:"column:inventory_id;type:int;not null" json:"inventory_id"`
	EmployeeID  int64      `gorm:"column:employee_id;type:int;not null" json:"employee_id"`
	Action      int64      `gorm:"column:action;type:tinyint(1);not null" json:"action"`
	CreateTime  time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	DeleteAt    *time.Time `gorm:"column:delete_at;type:datetime" json:"delete_at"`
	Amout       int64      `gorm:"column:amout;type:int;not null" json:"amout"`
}

// TableName InventoryInOut's table name
func (*InventoryInOut) TableName() string {
	return TableNameInventoryInOut
}
