// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	ID             int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name           string     `gorm:"column:name;type:varchar(200);not null" json:"name"`
	FarmID         int64      `gorm:"column:farm_id;type:int;not null" json:"farm_id"`
	Type           int64      `gorm:"column:type;type:int;not null" json:"type"`
	Company        string     `gorm:"column:company;type:varchar(200);not null" json:"company"`
	Sum            int64      `gorm:"column:sum;type:int;not null" json:"sum"`
	Price          float32    `gorm:"column:price;type:float;not null" json:"price"`
	UnitConversion float32    `gorm:"column:unit_conversion;type:float;not null" json:"unit_conversion"`
	StandardUnit   string     `gorm:"column:standard_unit;type:varchar(10);not null" json:"standard_unit"`
	ProductUnit    string     `gorm:"column:product_unit;type:varchar(10);not null" json:"product_unit"`
	DeleteAt       *time.Time `gorm:"column:delete_at;type:datetime" json:"delete_at"`
	MinimumLimit   int64      `gorm:"column:minimum_limit;type:int;not null" json:"minimum_limit"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
