// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID             int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	SubmitterID    int64      `gorm:"column:submitter_id;type:int;not null" json:"submitter_id"`
	SolverID       *int64     `gorm:"column:solver_id;type:int" json:"solver_id"`
	HenhouseID     int64      `gorm:"column:henhouse_id;type:int;not null" json:"henhouse_id"`
	Status         int64      `gorm:"column:status;type:int;not null" json:"status"`
	Type           int64      `gorm:"column:type;type:int;not null" json:"type"`
	Urgency        int64      `gorm:"column:urgency;type:int;not null" json:"urgency"`
	CreateTime     time.Time  `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time"`
	AcceptTime     *time.Time `gorm:"column:accept_time;type:datetime" json:"accept_time"`
	FinishTime     *time.Time `gorm:"column:finish_time;type:datetime" json:"finish_time"`
	SubmitDetails  *string    `gorm:"column:submit_details;type:varchar(500)" json:"submit_details"`
	SubmitImageURL *string    `gorm:"column:submit_image_url;type:varchar(500)" json:"submit_image_url"`
	SolveDetails   *string    `gorm:"column:solve_details;type:varchar(500)" json:"solve_details"`
	SolveImageURL  *string    `gorm:"column:solve_image_url;type:varchar(500)" json:"solve_image_url"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
