// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDevice = "device"

// Device mapped from table <device>
type Device struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MaintainerID int32     `gorm:"column:maintainer_id;not null" json:"maintainer_id"`
	HenhouseID   int32     `gorm:"column:henhouse_id;not null" json:"henhouse_id"`
	Status       int32     `gorm:"column:status;not null" json:"status"`
	Type         int32     `gorm:"column:type;not null" json:"type"`
	URL          string    `gorm:"column:url;not null" json:"url"`
	Mac          string    `gorm:"column:mac;not null" json:"mac"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	CreateTime   time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
