// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "employee"

// Employee mapped from table <employee>
type Employee struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Rank       int32     `gorm:"column:rank;not null" json:"rank"`
	Phone      string    `gorm:"column:phone;not null" json:"phone"`
	Openid     *string   `gorm:"column:openid" json:"openid"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
