// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEnterprise = "enterprise"

// Enterprise mapped from table <enterprise>
type Enterprise struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	Address          string    `gorm:"column:address;not null" json:"address"`
	SuperintendentID int32     `gorm:"column:superintendent_id;not null" json:"superintendent_id"`
	CreateTime       time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Enterprise's table name
func (*Enterprise) TableName() string {
	return TableNameEnterprise
}
