// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenStep = "hen_steps"

// HenStep mapped from table <hen_steps>
type HenStep struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID       string    `gorm:"column:uuid;not null" json:"uuid"`
	Mac        string    `gorm:"column:mac;not null" json:"mac"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	HenhouseID int32     `gorm:"column:henhouse_id;not null" json:"henhouse_id"`
	DaySteps   int32     `gorm:"column:day_steps;not null" json:"day_steps"`
	TotalSteps int32     `gorm:"column:total_steps;not null" json:"total_steps"`
	Rssi       int32     `gorm:"column:rssi;not null" json:"rssi"`
	Battery    int32     `gorm:"column:battery;not null" json:"battery"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName HenStep's table name
func (*HenStep) TableName() string {
	return TableNameHenStep
}
