// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenhouse = "henhouse"

// Henhouse mapped from table <henhouse>
type Henhouse struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FarmID     int32     `gorm:"column:farm_id;not null" json:"farm_id"`
	Longitude  float32   `gorm:"column:longitude;not null" json:"longitude"`
	Latitude   float32   `gorm:"column:latitude;not null" json:"latitude"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
	Sum        int32     `gorm:"column:sum;not null" json:"sum"`
}

// TableName Henhouse's table name
func (*Henhouse) TableName() string {
	return TableNameHenhouse
}
