// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHenhouseInOut = "henhouse_in_out"

// HenhouseInOut mapped from table <henhouse_in_out>
type HenhouseInOut struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	HenhouseID int32     `gorm:"column:henhouse_id;not null" json:"henhouse_id"`
	Amount     int32     `gorm:"column:amount;not null" json:"amount"`
	Days       int32     `gorm:"column:days;not null" json:"days"`
	Action     bool      `gorm:"column:action;not null" json:"action"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
	EmployeeID int32     `gorm:"column:employee_id;not null" json:"employee_id"`
	Sum        int32     `gorm:"column:sum;not null" json:"sum"`
}

// TableName HenhouseInOut's table name
func (*HenhouseInOut) TableName() string {
	return TableNameHenhouseInOut
}
