// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	ID             int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string     `gorm:"column:name;not null" json:"name"`
	FarmID         int32      `gorm:"column:farm_id;not null" json:"farm_id"`
	Type           int32      `gorm:"column:type;not null" json:"type"`
	Company        string     `gorm:"column:company;not null" json:"company"`
	Sum            int32      `gorm:"column:sum;not null" json:"sum"`
	Price          float32    `gorm:"column:price;not null" json:"price"`
	UnitConversion float32    `gorm:"column:unit_conversion;not null" json:"unit_conversion"`
	StandardUnit   string     `gorm:"column:standard_unit;not null" json:"standard_unit"`
	ProductUnit    string     `gorm:"column:product_unit;not null" json:"product_unit"`
	DeleteAt       *time.Time `gorm:"column:delete_at" json:"delete_at"`
	MinimumLimit   int32      `gorm:"column:minimum_limit;not null" json:"minimum_limit"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
