// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID             int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SubmitterID    int32      `gorm:"column:submitter_id;not null" json:"submitter_id"`
	SolverID       *int32     `gorm:"column:solver_id" json:"solver_id"`
	HenhouseID     int32      `gorm:"column:henhouse_id;not null" json:"henhouse_id"`
	Status         int32      `gorm:"column:status;not null" json:"status"`
	Type           int32      `gorm:"column:type;not null" json:"type"`
	Urgency        int32      `gorm:"column:urgency;not null" json:"urgency"`
	CreateTime     time.Time  `gorm:"column:create_time;not null" json:"create_time"`
	AcceptTime     *time.Time `gorm:"column:accept_time" json:"accept_time"`
	FinishTime     *time.Time `gorm:"column:finish_time" json:"finish_time"`
	SubmitDetails  *string    `gorm:"column:submit_details" json:"submit_details"`
	SubmitImageURL *string    `gorm:"column:submit_image_url" json:"submit_image_url"`
	SolveDetails   *string    `gorm:"column:solve_details" json:"solve_details"`
	SolveImageURL  *string    `gorm:"column:solve_image_url" json:"solve_image_url"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
