// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployeeAffiliation = "employee_affiliations"

// EmployeeAffiliation mapped from table <employee_affiliations>
type EmployeeAffiliation struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID   int32     `gorm:"column:employee_id;not null" json:"employee_id"`
	FarmID       int32     `gorm:"column:farm_id;not null" json:"farm_id"`
	EnterpriseID int32     `gorm:"column:enterprise_id;not null" json:"enterprise_id"`
	CreateTime   time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName EmployeeAffiliation's table name
func (*EmployeeAffiliation) TableName() string {
	return TableNameEmployeeAffiliation
}
