// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFarm = "farm"

// Farm mapped from table <farm>
type Farm struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EnterpriseID     int32     `gorm:"column:enterprise_id;not null" json:"enterprise_id"`
	SuperintendentID int32     `gorm:"column:superintendent_id;not null" json:"superintendent_id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	Address          string    `gorm:"column:address;not null" json:"address"`
	CreateTime       time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Farm's table name
func (*Farm) TableName() string {
	return TableNameFarm
}
