// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryInOut = "inventory_in_out"

// InventoryInOut mapped from table <inventory_in_out>
type InventoryInOut struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FarmID      int32      `gorm:"column:farm_id;not null" json:"farm_id"`
	Sum         int32      `gorm:"column:sum;not null" json:"sum"`
	InventoryID int32      `gorm:"column:inventory_id;not null" json:"inventory_id"`
	EmployeeID  int32      `gorm:"column:employee_id;not null" json:"employee_id"`
	Action      bool       `gorm:"column:action;not null" json:"action"`
	CreateTime  time.Time  `gorm:"column:create_time;not null" json:"create_time"`
	DeleteAt    *time.Time `gorm:"column:delete_at" json:"delete_at"`
	Amout       int32      `gorm:"column:amout;not null" json:"amout"`
}

// TableName InventoryInOut's table name
func (*InventoryInOut) TableName() string {
	return TableNameInventoryInOut
}
